# Generated by Django 5.0.4 on 2024-05-07 07:57

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=10)),
                ('name', models.TextField(default='c3bd189a-e448-42ec-8110-3ff7baee5252')),
                ('year', models.TextField(default='2024')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format(15 dig): '+999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact Number')),
                ('workplace', models.CharField(blank=True, default='NA', max_length=60, verbose_name='Workplace')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('duration', models.IntegerField(default=60)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField(max_length=128)),
                ('description', models.TextField(max_length=240)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hosts.cohort')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hosts.host')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
