# Generated by Django 5.0.4 on 2024-05-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'verbose_name': 'Cohort', 'verbose_name_plural': 'Cohorts'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': 'Host', 'verbose_name_plural': 'Hosts'},
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(default='d5318485-f3ac-46fc-bc9e-c0ae68db3bd0', max_length=128),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='year',
            field=models.CharField(default='2024', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
