# Generated by Django 5.0.4 on 2024-05-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_alter_cohort_options_alter_host_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(default='c9e54c66-ac81-4b2f-99cf-2283b0640643', max_length=128),
        ),
    ]
