# Generated by Django 5.0.4 on 2024-05-16 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='fingerprint',
            field=models.BinaryField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(default='fa8ec30d-95ae-4f56-a630-164a7553165d', max_length=128),
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(auto_now=True)),
                ('ended', models.TimeField(auto_now=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.CharField(blank=True, max_length=40)),
                ('fingerprint', models.BinaryField(max_length=512)),
                ('lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guests.guest')),
            ],
            options={
                'verbose_name': 'Marker',
                'verbose_name_plural': 'Markers',
            },
        ),
    ]
